backend:
  name: github
  repo: PopCoaster/popcoaster
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
media_folder: "images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Catégorie", name: "categorie", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Chapeau", name: "chapeau", widget: "text"}
      - {label: "Corps de l’article", name: "body", widget: "markdown"}
