backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://popcoaster.netlify.app"
display_url: "https://popcoaster.netlify.app"

collections:
  - name: "posts"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cat√©gorie", name: "categorie", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Chapeau", name: "chapeau", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
