backend:
  name: github
  repo: PopCoaster/popcoaster
  branch: main
  auth_type: token
  token: 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
  site_domain: https://popcoaster.github.io/popcoaster

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cat√©gorie", name: "category", widget: "string" }
      - { label: "Chapeau", name: "chapeau", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
